export const INCREASE_VISITOR = "INCREASE_VISITOR";
export const DECREASE_VISITOR = "DECREASE_VISITOR";
export const CHANGE_COLOR = "CHANGE_COLOR";

export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
